fix(api-model): avoid panic parsing build versions with a "-dirty" suffix (#3775)
## Bug description
The NICo API panicked at runtime

```
thread 'tokio-rt-worker' (7) panicked at crates/api-model/src/machine/upgrade_policy.rs:239:43:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }
stack backtrace:
```

The root cause is a combination of:
- default [VERSION
constructor](https://github.com/NVIDIA/infra-controller/blob/main/Makefile#L88)
which uses the following command that includes the `--dirty` key:
`VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null ||
echo dev)`
- `BuildVersion` parser which can't parse the default-generated version
string like: `v2.0.0-rc.2-9-g0401aad9f-dirty`

## Proposed solution

Strip the `-dirty` suffix before parsing BuildVersion if present.

## Related issues

## Type of Change
- [ ] **Add** - New feature or capability
- [ ] **Change** - Changes in existing functionality
- [x] **Fix** - Bug fixes
- [ ] **Remove** - Removed features or deprecated functionality
- [ ] **Internal** - Internal changes (refactoring, tests, docs, etc.)

## Breaking Changes
- [ ] **This PR contains breaking changes**

## Testing

- [x] Unit tests added/updated
- [ ] Integration tests added/updated
- [ ] Manual testing performed
- [ ] No testing required (docs, internal refactor, etc.)

Signed-off-by: Anatolii Kurotych <akurotych@gmail.com>